### ISSUE TITLE
Como rodar?

### ISSUE THREAD

**Issue by lucasmahle** [emersonjsouza/rails-todo-ajax#1]
Man, me da uma ajuda. Sou novo com Ruby.
Eu fiz git clone depois deis um bundle install, mas quando tento executar o rails server, ele retorna o manual de utilização. O que eu "esqueci" de fazer?

**Comment by emersonjsouza** [comment]
Tive o mesmo problema, também sou iniciante. Olha se tem a pasta bin.

**Comment by lucasmahle** [comment]
Não tem cara.

**Comment by emersonjsouza** [comment]
Pronto, adicionei a pasta no projeto.

**Comment by lucasmahle** [comment]
Valeu, em casa eu testo se rolou.
Abraço.

**Comment by emersonjsouza** [comment]
davi.figueira@uol.com.br
